### PR TITLE
Add OVN metrics to ocp-performance dashboard

### PR DESCRIPTION
**Pull request by smalleni**
Signed-off-by: Sai Sindhur Malleni <smalleni@redhat.com>

### CODE REVIEW

**Comment by smalleni** [comment]
@rsevilla87 PTAL, I'm able to import the JSON, but CI seems to be failing?

**Comment by jtaleric** [comment]
Small enhancement to the CI : ```
jtaleric at bolt in ~/code/arsenal/jsonnet on ovn△ $ for file in templates/*.jsonnet; do echo "Testing $file"; jsonnetfmt --test $file; echo "Result : "$?; done
Testing templates/api-performance-overview.jsonnet
Result : 0
Testing templates/etcd-on-cluster-dashboard.jsonnet
Result : 0
Testing templates/ocp-performance.jsonnet
Result : 2
Testing templates/pgbench-dashboard.jsonnet
Result : 0
Testing templates/uperf-perf.jsonnet
Result : 0
Testing templates/vegeta-wrapper.jsonnet
Result : 0
Testing templates/ycsb.jsonnet
Result : 0


```

**Comment by jtaleric** [comment]
@smalleni not sure if the spacing is coming through, but 

```
jtaleric at bolt in ~/code/arsenal/jsonnet on ovn△ $ jsonnetfmt -i templates/ocp-performance.jsonnet
jtaleric at bolt in ~/code/arsenal/jsonnet on ovn▲ $ git diff
diff --git a/jsonnet/templates/ocp-performance.jsonnet b/jsonnet/templates/ocp-performance.jsonnet
index 6d60d87..9387004 100644
--- a/jsonnet/templates/ocp-performance.jsonnet
+++ b/jsonnet/templates/ocp-performance.jsonnet
@@ -826,7 +826,7 @@ grafana.dashboard.new(
       ovnCNIDel { gridPos: { x: 12, y: 13, w: 12, h: 8 } },
       ovnFlowCount { gridPos: { x: 0, y: 21, w: 24, h: 12 } },
     ]
-   ), { gridPos: { x: 0, y: 0, w: 24, h: 1 } }
+  ), { gridPos: { x: 0, y: 0, w: 24, h: 1 } }
 )
 
 .addPanel(

```

**Comment by rsevilla87** [comment]
> @smalleni not sure if the spacing is coming through, but
> 
> ```
> jtaleric at bolt in ~/code/arsenal/jsonnet on ovn△ $ jsonnetfmt -i templates/ocp-performance.jsonnet
> jtaleric at bolt in ~/code/arsenal/jsonnet on ovn▲ $ git diff
> diff --git a/jsonnet/templates/ocp-performance.jsonnet b/jsonnet/templates/ocp-performance.jsonnet
> index 6d60d87..9387004 100644
> --- a/jsonnet/templates/ocp-performance.jsonnet
> +++ b/jsonnet/templates/ocp-performance.jsonnet
> @@ -826,7 +826,7 @@ grafana.dashboard.new(
>        ovnCNIDel { gridPos: { x: 12, y: 13, w: 12, h: 8 } },
>        ovnFlowCount { gridPos: { x: 0, y: 21, w: 24, h: 12 } },
>      ]
> -   ), { gridPos: { x: 0, y: 0, w: 24, h: 1 } }
> +  ), { gridPos: { x: 0, y: 0, w: 24, h: 1 } }
>  )
>  
>  .addPanel(
> ```

Yeah, there're linting issues in the code. @smalleni you can fix them with `make format`, I recommend to execute this command prior to open the PR, sorry I didn't mentiond it yesterday.
@jtaleric thanks for your suggestions for the CI improvement, will push them asap.

On the other hand, as the title says this PR addes some OVN related panels to the OCP dashboard. Do we want to have these panels included with dashboard, keep in mind that will fail in scenarios w/o OVN. Maybe we should consider creating a different dashboard for OVN. What do you think?

**Comment by jtaleric** [comment]
> > @smalleni not sure if the spacing is coming through, but
> > ```
> > jtaleric at bolt in ~/code/arsenal/jsonnet on ovn△ $ jsonnetfmt -i templates/ocp-performance.jsonnet
> > jtaleric at bolt in ~/code/arsenal/jsonnet on ovn▲ $ git diff
> > diff --git a/jsonnet/templates/ocp-performance.jsonnet b/jsonnet/templates/ocp-performance.jsonnet
> > index 6d60d87..9387004 100644
> > --- a/jsonnet/templates/ocp-performance.jsonnet
> > +++ b/jsonnet/templates/ocp-performance.jsonnet
> > @@ -826,7 +826,7 @@ grafana.dashboard.new(
> >        ovnCNIDel { gridPos: { x: 12, y: 13, w: 12, h: 8 } },
> >        ovnFlowCount { gridPos: { x: 0, y: 21, w: 24, h: 12 } },
> >      ]
> > -   ), { gridPos: { x: 0, y: 0, w: 24, h: 1 } }
> > +  ), { gridPos: { x: 0, y: 0, w: 24, h: 1 } }
> >  )
> >  
> >  .addPanel(
> > ```
> 
> Yeah, there're linting issues in the code. @smalleni you can fix them with `make format`, I recommend to execute this command prior to open the PR, sorry I didn't mentiond it yesterday.
> 
> @jtaleric thanks for your suggestions for the CI improvements, I will push them asap.
> 
> On the other hand, as the title says this PR addes some OVN related panels to the OCP dashboard. Do we want to have these panels included with dashboard, keep in mind that will fail in scenarios w/o OVN. Maybe we should consider creating a different dashboard for OVN. What do you think?

Maybe the panel comes collapsed at first, and if the user knows their deployment has OVN, they open it up?

**Comment by rsevilla87** [comment]
> > > @smalleni not sure if the spacing is coming through, but
> > > ```
> > > jtaleric at bolt in ~/code/arsenal/jsonnet on ovn△ $ jsonnetfmt -i templates/ocp-performance.jsonnet
> > > jtaleric at bolt in ~/code/arsenal/jsonnet on ovn▲ $ git diff
> > > diff --git a/jsonnet/templates/ocp-performance.jsonnet b/jsonnet/templates/ocp-performance.jsonnet
> > > index 6d60d87..9387004 100644
> > > --- a/jsonnet/templates/ocp-performance.jsonnet
> > > +++ b/jsonnet/templates/ocp-performance.jsonnet
> > > @@ -826,7 +826,7 @@ grafana.dashboard.new(
> > >        ovnCNIDel { gridPos: { x: 12, y: 13, w: 12, h: 8 } },
> > >        ovnFlowCount { gridPos: { x: 0, y: 21, w: 24, h: 12 } },
> > >      ]
> > > -   ), { gridPos: { x: 0, y: 0, w: 24, h: 1 } }
> > > +  ), { gridPos: { x: 0, y: 0, w: 24, h: 1 } }
> > >  )
> > >  
> > >  .addPanel(
> > > ```
> > 
> > 
> > Yeah, there're linting issues in the code. @smalleni you can fix them with `make format`, I recommend to execute this command prior to open the PR, sorry I didn't mentiond it yesterday.
> > @jtaleric thanks for your suggestions for the CI improvements, I will push them asap.
> > On the other hand, as the title says this PR addes some OVN related panels to the OCP dashboard. Do we want to have these panels included with dashboard, keep in mind that will fail in scenarios w/o OVN. Maybe we should consider creating a different dashboard for OVN. What do you think?
> 
> Maybe the panel comes collapsed at first, and if the user knows their deployment has OVN, they open it up?

Yeah, is a possibility. Want to have a second opinion, what do you think @smalleni ?

**Comment by smalleni** [comment]
It'a already a collapsed row. I think going forward we will have more clusters with oVN too right? I'm OK with creating a new dashboard, just didn't think it was worth it since it's collapsible anyway and would just be empty without OVN.

**Review by rsevilla87 — APPROVED** [review]
LGTM!

**Pull request merged**
